FROM  i386/ubuntu:trusty
RUN apt-get update && \
    apt-get upgrade && \
    apt-get install -y git build-essential   gcc  binutils  automake libtool make cmake pkg-config && \
    apt-get install -y libgtk2.0-dev libjpeg-dev libpng12-dev libfreetype6-dev libsqlite3-dev libxml2-dev wget 

RUN  cd ~/ && \ 
     wget http://www.minigui.org/downloads/freetype-2.3.9-fm20100818.tar.gz && \
     tar xzf freetype-2.3.9-fm20100818.tar.gz && \
	 cd freetype-2.3.9-fm20100818 && \
	 ./configure && \
	 make && \
	 make install && \
     git clone https://github.com/maikebing/minigui2.4.git && \
    cd  ./minigui2.4/  && \
	chmod 777 ./rebuildx86 && \
 	./rebuildx86 && \
	make clean  && \
	make && \
	make install 




